apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secret
              key: APP_KEY
        - name: DB_CONNECTION
          value: {{ .Values.database.connection | quote }}
        - name: DB_HOST
          value: {{ .Values.database.host | quote }}
        - name: DB_PORT
          value: {{ .Values.database.port | quote }}
        - name: DB_DATABASE
          value: {{ .Values.database.name | quote }}
        - name: DB_USERNAME
          value: {{ .Values.database.username | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secret
              key: DB_PASSWORD
