apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.appKey | quote  }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.mysqlRootPassword | quote }}
